"use client";
import type {
  GarmentFieldValue,
  GarmentFieldValues,
  RuntimeGarmentField,
} from "@/lib/garment-form-runtime";

function multiselectValues(value: GarmentFieldValue): string[] {
  return Array.isArray(value)
    ? value.filter((option): option is string => typeof option === "string")
    : [];
}

export function GarmentFormFields({ fields, values, errors = {}, disabled = false, showSectionHeadings = true, onChange }: { fields: RuntimeGarmentField[]; values: GarmentFieldValues; errors?: Record<string, string>; disabled?: boolean; showSectionHeadings?: boolean; onChange: (code: string, value: GarmentFieldValue) => void }) {
  const groups = fields.reduce<Record<string, RuntimeGarmentField[]>>((all, field) => { (all[field.sectionName] ??= []).push(field); return all; }, {});
  return <>{Object.entries(groups).map(([section, group]) => <section key={section} className="mb-4">{showSectionHeadings && <h4 className="mb-2 text-[15px] font-semibold text-ink">{section}</h4>}<div className="grid grid-cols-2 gap-3 md:grid-cols-3">{group.map(field => <label key={field.code} className="flex flex-col gap-1 text-[13px] font-medium text-ink-muted"><span>{field.name}{field.required && <b className="ml-1 text-chip-red-fg">*</b>}{field.unit && ` (${field.unit})`}</span>{field.inputType === "textarea" ? <textarea disabled={disabled} required={field.required} value={(values[field.code] as string | null) ?? ""} placeholder={field.placeholder ?? undefined} onChange={e => onChange(field.code, e.target.value)} className="min-h-16 rounded-md border border-border bg-white p-2 text-sm text-ink" /> : field.inputType === "select" ? <select disabled={disabled} required={field.required} value={(values[field.code] as string | null) ?? ""} onChange={e => onChange(field.code, e.target.value)} className="h-10 rounded-md border border-border bg-white px-2 text-sm text-ink"><option value="">Select…</option>{field.options.map(option => <option key={option}>{option}</option>)}</select> : field.inputType === "multiselect" ? <div className="space-y-1 rounded-md border border-border bg-white p-2">{field.options.map(option => { const current = multiselectValues(values[field.code]); const selected = current.includes(option); return <label className="flex items-center gap-2 text-sm text-ink" key={option}><input disabled={disabled} type="checkbox" checked={selected} onChange={() => onChange(field.code, selected ? current.filter(value => value !== option) : [...current, option])} />{option}</label>; })}</div> : field.inputType === "checkbox" ? <span className="flex h-10 items-center gap-2"><input disabled={disabled} type="checkbox" checked={values[field.code] === true} onChange={e => onChange(field.code, e.target.checked)} /><span className="text-sm text-ink">Yes</span></span> : <input disabled={disabled} required={field.required} type={field.inputType === "number" ? "number" : "text"} min={field.min ?? undefined} max={field.max ?? undefined} step={field.decimalPlaces === null ? undefined : 1 / 10 ** field.decimalPlaces} value={(values[field.code] as string | number | null) ?? ""} placeholder={field.placeholder ?? undefined} onChange={e => onChange(field.code, field.inputType === "number" ? (e.target.value === "" ? null : Number(e.target.value)) : e.target.value)} className="h-10 rounded-md border border-border bg-white px-2 text-sm text-ink" />}{errors[field.code] && <span className="text-xs text-chip-red-fg">{errors[field.code]}</span>}</label>)}</div></section>)}</>;
}
